--- /home/hjj/Downloads/linux-master/kernel/gcov/Makefile
+++ /home/hjj/Downloads/linux-fslc-4.17.4/kernel/gcov/Makefile
@@ -4,5 +4,3 @@
 obj-y := base.o fs.o
 obj-$(CONFIG_GCOV_FORMAT_3_4) += gcc_3_4.o
 obj-$(CONFIG_GCOV_FORMAT_4_7) += gcc_4_7.o
-obj-$(CONFIG_GCOV_FORMAT_AUTODETECT) += $(call cc-ifversion, -lt, 0407, \
-							gcc_3_4.o, gcc_4_7.o)
