--- /home/hjj/Downloads/linux-fslc-4.17.4/kernel/printk/Makefile
+++ /home/hjj/Downloads/linux-fslc-4.1.44/kernel/printk/Makefile
@@ -1,2 +1,3 @@
 obj-y	= printk.o
+obj-$(CONFIG_PRINTK)	+= printk_safe.o
 obj-$(CONFIG_A11Y_BRAILLE_CONSOLE)	+= braille.o
