--- /home/hjj/Downloads/linux-fslc-4.17.4/kernel/gcov/Makefile
+++ /home/hjj/Downloads/linux-fslc-4.1.44/kernel/gcov/Makefile
@@ -1,3 +1,4 @@
+# SPDX-License-Identifier: GPL-2.0
 ccflags-y := -DSRCTREE='"$(srctree)"' -DOBJTREE='"$(objtree)"'
 
 obj-y := base.o fs.o
