--- /home/hjj/Downloads/linux-master/kernel/livepatch/Makefile
+++ /home/hjj/Downloads/linux-fslc-4.1.44/kernel/livepatch/Makefile
@@ -1,3 +1,3 @@
 obj-$(CONFIG_LIVEPATCH) += livepatch.o
 
-livepatch-objs := core.o
+livepatch-objs := core.o patch.o shadow.o transition.o
