--- /home/hjj/Downloads/linux-fslc-4.17.4/kernel/events/Makefile
+++ /home/hjj/Downloads/linux-fslc-4.1.44/kernel/events/Makefile
@@ -1,3 +1,4 @@
+# SPDX-License-Identifier: GPL-2.0
 ifdef CONFIG_FUNCTION_TRACER
 CFLAGS_REMOVE_core.o = $(CC_FLAGS_FTRACE)
 endif
